platform:ios,’8.0’
target "Demo1" do
pod 'FMDB', '~> 2.7.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.0.0'
pod 'GPUImage', '~> 0.1.7'
use_frameworks!
pod 'EVGPUImage2', '~> 0.1.0'
end
